src/main/java/com/lea/books/entity/catalog/Author.java
package com.lea.books.entity.catalog;

import javax.persistence.*;

@Entity
@Table(name="Author")
public class Author {
    @Id
    @GeneratedValue
    @Column(name="id")
    private int id;

    @Column(name="name")
    private String name;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

src/main/java/com/lea/books/entity/catalog/Book.java
package com.lea.books.entity.catalog;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name="Book")
@SuppressWarnings("unused")
public class Book {
    @Id
    @GeneratedValue
    @Column(name="id")
    private int id;

    @Column(name="name")
    private String name;

    @Column(name="article")
    private String article;

    @ManyToOne
    @JoinColumn(name="section", nullable = true)
    private Section section;

    @Column(name="yearPublication")
    private int yearPublication;

    @Column(name="numberPublication")
    private int numberPublication;

    @Column(name="isbn")
    private String isbn;

    @Column(name="countPages")
    private int countPages;

    @Column(name="formatW")
    private int formatW;

    @Column(name="formatH")
    private int formatH;

    @Column(name="description")
    private String description;

    @Column(name="price")
    private double price;

    @Column(name="remains")
    private int remains;

    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinTable(name="BookCategories",
    joinColumns={@JoinColumn(name="idBook")},
    inverseJoinColumns={@JoinColumn(name="idCategory")})
    private List<Category> categories=new ArrayList<>();

    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @Fetch(FetchMode.SUBSELECT)
    @JoinTable(name="BookAuthors",
    joinColumns={@JoinColumn(name="idBook",referencedColumnName="id")},
    inverseJoinColumns={@JoinColumn(name="idAuthor",referencedColumnName="id")})
    private List <Author> authors=new ArrayList<>();

    @ManyToOne
    @JoinColumn(name="imageSrc", referencedColumnName = "name",insertable = false, updatable = false)
    private Image image;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getArticle() {
        return article;
    }

    public void setArticle(String article) {
        this.article = article;
    }

    public List<Author> getAuthors() {
        return authors;
    }

    public void setAuthors(List<Author> authors) {
        this.authors.clear();
        this.authors.addAll(authors);
    }

    public void setAuthor(Author author){
        this.authors.clear();
        this.authors.add(author);
    }

    public Section getSection() {
        return section;
    }

    public void setSection(Section section) {
        this.section = section;
    }

    public int getYearPublication() {
        return yearPublication;
    }

    public void setYearPublication(int yearOfPublication) {
        this.yearPublication = yearOfPublication;
    }

    public int getNumberPublication() {
        return numberPublication;
    }

    public void setNumberPublication(int numberPublication) {
        this.numberPublication = numberPublication;
    }

    public String getIsbn() {
        return isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public int getCountPages() {
        return countPages;
    }

    public void setCountPages(int countPages) {
        this.countPages = countPages;
    }

    public int getFormatW() {
        return formatW;
    }

    public void setFormatW(int formatW) {
        this.formatW = formatW;
    }

    public int getFormatH() {
        return formatH;
    }

    public void setFormatH(int formatH) {
        this.formatH = formatH;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<Category> getCategories() {
        return categories;
    }

    public void setCategories(List<Category> categories) {
        this.categories = categories;
    }

    public void setCategory(Category category){
        this.categories.add(category);
    }


    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public int getRemains() {
        return remains;
    }

    public void setRemains(int remains) {
        this.remains = remains;
    }

    public String getImageSrc() {
        return (image != null)?image.getLink():"";
    }

    public Image getImage() {
        return image;
    }

    public void setImage(Image image) {
        this.image = image;
    }

    public String getAuthorsName(){
        String result = "";

        if(authors!=null) {
            for (Author author: authors) {
                result += (result.isEmpty() ? "" : ", ") + author.getName();
            }
        }

        return result;
    }
}

src/main/java/com/lea/books/model/cart/Currency.java
package com.lea.books.model.cart;

public class Currency {
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return name;
    }
}

src/main/java/com/lea/books/model/catalog/BookSet.java
package com.lea.books.model.catalog;
import com.lea.books.entity.catalog.Book;
import com.lea.books.entity.catalog.Category;

import java.util.List;

public class BookSet {

    private List<Book> books;
    private Category category;

    public Category getGroup() {
        return category;
    }

    public List<Book> getBooks() {
        return books;
    }

    public void setBooks(List<Book> books) {
        this.books = books;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }
}

src/main/java/com/lea/books/controller/cart/CartController.java
package com.lea.books.controller.cart;

import com.lea.books.entity.catalog.Book;
import com.lea.books.model.cart.Cart;
import com.lea.books.service.cart.CartService;
import com.lea.books.service.catalog.BookService;

import com.lea.books.service.system.RequestService;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletRequest;


@Controller
public class CartController {
    @Autowired
    BookService bookService;

    @Autowired
    CartService cartService;

    @Autowired
    RequestService requestService;

    private static final Logger logger = Logger.getLogger(CartController.class);

    @ResponseBody
    @RequestMapping(value = {"/cart/add","/cart/qw/add"}, method = RequestMethod.GET)
    public String addCartItem(@RequestParam("id") String _id, HttpServletRequest request){
        int id = parseID(_id);
        Cart cart = requestService.getCart(request);

        if(id>0) {
            Book book = bookService.selectById(id);
            cartService.addCartItem(cart, book, 1);
            logger.debug("Cart update: id="+id);
        }

        return cart.toJson();
    }

    @ResponseBody
    @RequestMapping(value = {"/cart/update"}, method = RequestMethod.GET)
    public String updateCartItem(@RequestParam("id") String _id, @RequestParam("count") String _count, HttpServletRequest request){
        int id = parseID(_id);
        int count = parseCount(_count);
        Cart cart = requestService.getCart(request);

        if(id > 0){
            Book book = bookService.selectById(id);
            cartService.updateCartItem(cart, book, count);
            logger.debug("Cart update: id="+id+", count="+count);
        }

        return cart.toJson();
    }

    @ResponseBody
    @RequestMapping(value = {"/cart/delete"}, method = RequestMethod.GET)
    public String deleteCartItem(@RequestParam("id") String _id, HttpServletRequest request){
        int id = parseID(_id);
        Cart cart = requestService.getCart(request);

        if(id > 0){
            cartService.deleteCartItem(cart, id);
            logger.debug("Cart update: id="+id);
        }

        return cart.toJson();
    }

    @ResponseBody
    @RequestMapping(value = {"/cart"}, method = RequestMethod.GET)
    public String getCart(HttpServletRequest request){
        Cart cart = requestService.getCart(request);
        return cart.toJson();
    }

    private int parseID(String _id){
        int id=0;
        try {
            id = Integer.parseInt(_id);
        } catch (Exception e) {
            logger.error("ID (" + _id + ") is not a numerical value",e);
        }

        if(logger.isDebugEnabled()){
            logger.debug("Request param: id = " + id);
        }
        return id;
    }

    private int parseCount(String _count){
        int count = 0;
        try {
            count = Integer.parseInt(_count);
        } catch (Exception e) {
            logger.error("Count (" + _count + ") is not a numerical value",e);
        }
        return count;
    }
}

src/main/java/com/lea/books/controller/catalog/BookController.java
package com.lea.books.controller.catalog;

import com.lea.books.entity.catalog.Book;
import com.lea.books.service.catalog.BookService;
import com.lea.books.service.ui.BreadcrumbsBuilder;
import com.lea.books.utils.ResourceUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.apache.log4j.Logger;

@Controller
@RequestMapping(value = {"/book"})
public class BookController{
    @Autowired
    BookService bookService;

    @Autowired
    BreadcrumbsBuilder breadcrumbsBuilder;

    @Autowired
    ResourceUtils resourceUtils;

    private static final Logger logger = Logger.getLogger(BookController.class);

    @RequestMapping(method = RequestMethod.GET)
    public String showBookPage(@RequestParam("id") String _id, Model model) {
        int id = 0;

        try {
            id = Integer.parseInt(_id);
        } catch (NumberFormatException e) {
            logger.warn("ID (" + _id + ") is not a numerical value",e);
        }

        if(id<=0){
            logger.warn("Ignored empty ID");
            return "error.catalog";
        }

        logger.debug("ID = " + id);

        Book book = bookService.selectById(id);
        if(book==null){
            logger.warn("ID (" + _id + ") book is not found");
            return "error.catalog";
        }


        model.addAttribute("book", book);
        model.addAttribute("sectionPath", breadcrumbsBuilder.build(book));
        resourceUtils.makeResources(bookService.getResources(book));

        return "view.book";
    }

}

src/main/java/com/lea/books/controller/catalog/CatalogController.java
package com.lea.books.controller.catalog;

import com.lea.books.model.catalog.CatalogBranch;
import com.lea.books.service.catalog.*;
import com.lea.books.service.ui.BreadcrumbsBuilder;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

@Controller
public class CatalogController{
    @Autowired
    CatalogService catalogService;

    @Autowired
    BreadcrumbsBuilder breadcrumbsBuilder;

    private static final Logger logger = Logger.getLogger(CatalogController.class);

    @RequestMapping(value = {"/catalog"}, method = RequestMethod.GET)
    public String showCatalog(Model model){
        List<CatalogBranch> branches = catalogService.buildBranches(3);
        logger.debug("Catalog branches count:" + branches.size());

        model.addAttribute("catalogTree", branches);
        model.addAttribute("sectionPath", breadcrumbsBuilder.build());

        return "view.catalog";
    }
}

src/main/java/com/lea/books/controller/catalog/CategoryController.java
package com.lea.books.controller.catalog;

import com.lea.books.entity.catalog.Book;
import com.lea.books.entity.catalog.Category;
import com.lea.books.model.catalog.BookSet;
import com.lea.books.service.catalog.BookService;
import com.lea.books.service.catalog.CategoryService;

import com.lea.books.service.ui.BreadcrumbsBuilder;
import com.lea.books.utils.ResourceUtils;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.ArrayList;
import java.util.List;

@Controller
public class CategoryController{
    @Autowired
    CategoryService categoryService;

    @Autowired
    BookService bookService;

    @Autowired
    ResourceUtils resourceUtils;

    @Autowired
    BreadcrumbsBuilder breadcrumbsBuilder;

    private static final Logger logger = Logger.getLogger(CategoryController.class);
    private static final String VIEW_NAME_LIST = "view.bookList";
    private static final String VIEW_NAME_SETS = "view.bookSets";

    @RequestMapping(value = {"/category"}, method = RequestMethod.GET)
    public String showBookList(@RequestParam("id") String _id, Model model) {
        int id = 0;

        try {
            id = Integer.parseInt(_id);
        } catch (Exception e) {
            logger.warn("ID (" + _id + ") is not a numerical value",e);
        }

        if(id <= 0) {
            logger.warn("Ignored empty ID");
            return VIEW_NAME_LIST;
        }

        logger.debug("ID = " + id);

        Category category = categoryService.selectById(id);
        List<Book>bookList = bookService.selectByCategory(category);

        model.addAttribute("section", category);
        model.addAttribute("bookList", bookList);
        model.addAttribute("sectionPath", breadcrumbsBuilder.build(category));
        resourceUtils.makeResources(bookService.getResources(bookList));

        return VIEW_NAME_LIST;
    }

    @RequestMapping(value = {"/topsales"}, method = RequestMethod.GET)
    public String showBookListCategoryTopSales(Model model) {
        Category category = categoryService.topSalesCategory();

        if(category == null){
            model.addAttribute("sectionPath", breadcrumbsBuilder.build());
            logger.warn("Category is empty");
            return VIEW_NAME_LIST;
        }

        logger.debug("ID = " + category.getId());
        List<Book>bookList = bookService.selectByCategory(category);

        model.addAttribute("section",       category);
        model.addAttribute("bookList",      bookList);
        model.addAttribute("sectionPath", breadcrumbsBuilder.build(category));
        resourceUtils.makeResources(bookService.getResources(bookList));

        return VIEW_NAME_LIST;
    }

    @RequestMapping(value = {"/novelty"}, method = RequestMethod.GET)
    public String showBookListCategoryNovelty(Model model) {
        Category category = categoryService.noveltyCategory();

        if(category == null) {
            model.addAttribute("sectionPath", breadcrumbsBuilder.build());
            logger.warn("Category is empty");
            return VIEW_NAME_LIST;
        }

        logger.debug("ID = " + category.getId());
        List<Book>bookList = bookService.selectByCategory(category);

        model.addAttribute("section",       category);
        model.addAttribute("bookList",      bookList);
        model.addAttribute("sectionPath", breadcrumbsBuilder.build(category));
        resourceUtils.makeResources(bookService.getResources(bookList));

        return VIEW_NAME_LIST;
    }

    @RequestMapping(value = {"/recommended"}, method = RequestMethod.GET)
    public String showBookListCategoryRecommended(Model model){
        Category noveltyCategory = categoryService.noveltyCategory();
        Category topSalesCategory = categoryService.topSalesCategory();

        if(noveltyCategory == null && topSalesCategory == null){
            logger.warn("Category \"novelty\" is empty");
            logger.warn("Category \"topSales\" is empty");
            return VIEW_NAME_SETS;
        }

        List<Category> categories = new ArrayList<>();
        if(noveltyCategory != null){
            logger.debug("ID = {" + noveltyCategory.getId());
            categories.add(noveltyCategory);
        }
        else {
            logger.warn("Category \"novelty\" is empty");
        }

        if(topSalesCategory != null){
            categories.add(topSalesCategory);
            logger.debug("ID = {" + topSalesCategory.getId());
        }
        else {
            logger.warn("Category \"topSales\" is empty");
        }

        List<BookSet> bookSets = bookService.buildBookSets(categories,10);
        model.addAttribute("bookSets", bookSets);
        resourceUtils.makeResources(bookService.getResourcesList(bookSets));

        return VIEW_NAME_SETS;
    }
}

src/main/webapp/WEB-INF/views/titles/content/catalog/book-list.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>

<!--BOOK LIST-->
<div class="main-content__section">
    <c:forEach var="book" items="${bookList}">
        <div class="book-item">
            <div class="item-image">
                <a href="<c:url value="/book?id=${book.id}"/>">
                    <div class="item-image-view">
                        <img src="<c:url value="${book.imageSrc}"/>" alt="${book.name}">
                    </div>
                </a>
            </div>

            <div class="item-content">
                <a href="<c:url value="/book?id=${book.id}"/>">
                    <div class="title item-h1">${book.name}</div>
                </a>

                <span class="price">
                    <fmt:formatNumber type="number" minFractionDigits="2" value="${book.price}"/>
                    <em>${currencyApp}</em>
                </span>

                <button class="ibutton-quickbuy" type="submit" name="buyfromcatalog" onclick="cartEventHandler.quickBuy('${book.id}')">
                </button>
            </div>
        </div>
    </c:forEach>
</div>

src/main/webapp/WEB-INF/views/titles/content/catalog/book-top.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>

<div class="main-content__section">
    <c:forEach var="bookSet" items="${bookSets}">
        <div class="heading">
            <span>${bookSet.group.name}</span>
        </div>
        <span class="more-link">
            <a href="<c:url value="/category?id=${bookSet.group.id}"/>">
                Весь список
            </a>
        </span>

        <div class="scrollWrapper">
            <div class="scrollableArea">
                <c:forEach var="book" items="${bookSet.books}">
                    <div class="book-item">
                        <div class="item-image">
                            <a href="<c:url value="/book?id=${book.id}"/>">
                                <div class="item-image-view">
                                    <img src="<c:url value="${book.imageSrc}"/>" alt="${book.name}">
                                </div>
                            </a>
                        </div>

                        <div class="item-content">
                            <a href="<c:url value="/book?id=${book.id}"/>">
                                <div class="title item-h1">${book.name}</div>
                            </a>

                            <span class="price">
                                <fmt:formatNumber type="number" minFractionDigits="2" value="${book.price}"/>
                                <em>${currencyApp}</em>
                            </span>


                            <button class="ibutton-quickbuy" type="submit" name="buyfromcatalog" onclick="cartEventHandler.quickBuy('${book.id}')">
                            </button>
                        </div>
                    </div>
                </c:forEach>
            </div>
        </div>
    </c:forEach>
</div>

src/main/webapp/WEB-INF/views/titles/content/catalog/book.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>


<div class="main-content">
    <div class="container" style="display: table">
        <div class="container-left" style="display: table-cell">
            <img class="image-view" src="<c:url value="${book.imageSrc}"/>" title="" alt="" border="0" align=""/>
            <div class="image-text">Артикул: <span class="highlight">${book.article}</span></div>
        </div>

        <div class="container-right" style="display: table-cell">
            <div class="container-header">
                <a class="header-h1" href="<c:url value="/book?id=${book.id}"/>">${book.name}</a>
                <div class="header-h2" >
                    ${book.authorsName}
                </div>
            </div>

            <div class="property-list">
                <div>Год издания: ${book.yearPublication}</div>
                <div>Номер издания: ${book.numberPublication}</div>
                <div>В наличии: ${book.remains}</div>
                <div>ISBN: ${book.isbn}</div>
                <div>Количество страниц: ${book.countPages}</div>
                <div>Формат: ${book.formatW} x ${book.formatH}</div>
            </div>

            <div class="action-section">
                <div class="price">
                    <fmt:formatNumber type="number" minFractionDigits="2" value="${book.price}"/>
                    <em>${currencyApp}</em>
                </div>

                <button type="submit" class="clear" onclick="cartEventHandler.quickBuy('${book.id}')">
                    <div class="btn ibutton-orange ibutton-buy">Купить</div>
                </button>
            </div>
        </div>
    </div>

    <div class="description">
        <div class="h1">Описание книги:</div>
        <div class="text1">${book.description}</div>
    </div>
</div>

src/main/webapp/WEB-INF/views/titles/content/catalog/catalog.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>

<div class="catalog-section">
    <c:forEach var="catalogBranch" items="${catalogTree}">
        <div class="catalog-branch">
            <div class="branch-header">
                <a href="<c:url value="/section?id=${catalogBranch.section.id}"/>">
                    ${catalogBranch.section.name}
                </a>
            </div>

            <ul class="branch-level-h1">
                <c:forEach var="subBranch" items="${catalogBranch.subBranches}">
                    <li>
                        <a href="<c:url value="/section?id=${subBranch.section.id}"/>">
                            ${subBranch.section.name}
                        </a>
                    </li>

                    <ul class="branch-level-h2">
                        <c:forEach var="subBranch" items="${subBranch.subBranches}">
                            <li>
                                <a href="<c:url value="/section?id=${subBranch.section.id}"/>">
                                    ${subBranch.section.name}
                                </a>
                            </li>
                        </c:forEach>
                    </ul>
                </c:forEach>
            </ul>
        </div>
    </c:forEach>
</div>